/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    // 'a',
    {
      type: 'category',
      label: 'Prepare',
      items: ['prepare/install-rooch'],
    },
    {
      type: 'category',
      label: 'Concept',
      items: [
        'concept/packages',
        'concept/manifest',
        'concept/address',
        'concept/account',
        'concept/transaction',
      ]
    },
    {
      type: 'category',
      label: 'Move Basics',
      items: [
        'move-basics/module',
        'move-basics/comment',
        'move-basics/primitive-type',
        'move-basics/address',
        'move-basics/expression',
        'move-basics/struct',
        'move-basics/ability-intro',
        'move-basics/drop-ability',
        'move-basics/vector',
        'move-basics/string',
        'move-basics/control-flow',
        'move-basics/function',
        'move-basics/assert-and-abort',
        'move-basics/copy-ability',
        'move-basics/generics',
      ]
    },
    {
      // type: 'category',
      type: 'autogenerated',
      dirName: 'move-advanced',
      // label: 'Move Advanced',
      // items: [
        // 'move-advanced/object/rooch-object',
        // '<++>',
        // '<++>',
      // ]
    }
  ],
};

export default sidebars;
